# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cff3f4abddf01f01f94f8648264540ecad1d3bf6774e520803501e8953ed96a08e8298a32afa58104dc67eb790a4c6605888d2bbd37a4a10c80cce751b7b1070

test:
  secret_key_base: d6561a4670786cc4a747127683d0e30e15a3e7837516ee22301389927dd67fee4c45e9462b812b257f1effb423b62cafbb39dd5fa77550eb9742399df54d7bf8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
